forcedotcom/salesforcedx-vscode-automation-tests-redhat

test/specs/auraLsp.e2e.ts, test/specs/soql.e2e.ts, test/utilities/lwcUtils.ts, test/utilities/testUtils.ts, test/utilities/workbench.ts
- Adds test file for soql
- Adds test file for auraLsp
- typos and more logging
@W-17032852@
[Test run](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/11450014494/job/31856702741) ✅
=> feat: soql and auraLsp tests

test/specs/apexLsp.e2e.ts, test/specs/lwcLsp.e2e.ts, test/specs/visualforceLsp.e2e.ts, test/utilities/apexUtils.ts, test/utilities/lwcUtils.ts, test/utilities/outputView.ts, test/utilities/visualforceUtils.ts
Adds test file for lwcLsp
Adds test file for visualforceLsp
@W-17035065@
[Test run](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/11453333853) ✅
=> feat: lwcLsp and visualforceLsp tests

test/specs/sfdxProjectJson.e2e.ts, test/utilities/miscellaneous.ts
Adds test file for sfdxProjectJson
@W-17039293@
[Test run](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/11465932321) ✅
=> feat: sfdxProjectJson test in redhat

test/specs/authentication.e2e.ts
Adds test file for authentication
@W-17039188@
[Test run](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/11486260171) ✅
=> feat: authentication test in redhat

test/specs/templates.e2e.ts, test/utilities/miscellaneous.ts, test/utilities/sideBar.ts
Adds test file for templates
@W-17041184@
[Test run](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/11486968126/job/31970434295) ✅
=> feat: templates test in redhat

test/selfSpecs/cliCommands.test.ts, test/selfSpecs/settings.test.ts, test/specs/deployAndRetrieve.e2e.ts, test/specs/orgBrowser.e2e.ts, test/utilities/commandPrompt.ts, test/utilities/notifications.ts, test/utilities/outputView.ts, test/utilities/settings.ts
Add deployAndRetrieve test file
@W-17055686@
[Test run](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/11529583369/job/32098403342) ✅
=> feat: deployAndRetrieve e2e test in redhat

test/specs/pushAndPull.e2e.ts, test/utilities/commandPrompt.ts
- Adds pushAndPull test file
@W-17055716@
[Test run](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/11534719839/job/32109047550) ✅
=> feat: pushAndPull test in redhat

test/specs/runLwcTests.e2e.ts, test/utilities/cliCommands.ts, test/utilities/outputView.ts, test/utilities/terminalView.ts, test/utilities/testUtils.ts, test/utilities/workbench.ts
Adds runLwcTests test file
@W-17041388@
[Test run](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/11537985452)
=> feat: runLwcTests test in redhat

.mocharc.json, test/selfSpecs/notifications.test.ts, test/specs/runApexTests.e2e.ts, test/testSetup.ts, test/utilities/apexUtils.ts, test/utilities/notifications.ts, test/utilities/outputView.ts, test/utilities/testUtils.ts, test/utilities/textEditorView.ts
Add runApexTests E2E test file
@W-17055421@
[Test run](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/11583125251/job/32247640361) ✅
=> feat: runApexTests test in redhat

test/specs/debugApexTests.e2e.ts, test/specs/runApexTests.e2e.ts, test/utilities/testUtils.ts
Add debugApexTests E2E test file
@W-17055444@
[Test run](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/11615837086) ✅
=> feat: debugApexTests test in redhat

test/specs/metadataDeployRetrieve.e2e.ts, test/utilities/miscellaneous.ts, test/utilities/textEditorView.ts
Add metadataDeployRetrieve E2E test file
@W-17055489@
[Test run](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/11696584715/job/32573931523) ✅
=> feat: metadataDeployRetrieve test in redhat

test/specs/apexActions.e2e.ts
- Adds Apex Actions e2e test
@W-17236448@, @W-17236508@
=> feat: creat apex actions commands

test/specs/debugLwcTests.e2e.ts
@W-17379175@
Test run: https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/12185406934/job/33991585156 ✅
=> fix: debug lwc tests on windows

test/utilities/cliCommands.ts
[Test run](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/12892471704/job/35946757041)
=> fix for lwc tests

test/specs/pushAndPull.e2e.ts, test/testSetup.ts
@W-17854585@
Test run: [Deploy and Retrieve End to End Tests](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/13937169155) ✅
=> fix: W-17854585  - view changes in default org

.vscode/tasks.json, README.md, test/environmentSettings.ts, test/test-setup-and-runner.ts
=> chore: W-18077338 - update README

test/utilities/extensionUtils.ts, test/utilities/miscellaneous.ts
@ W-18078038@ 
remove unused vars
=> [W-18078038] chore: remove unused vars

test/specs/deployAndRetrieve.e2e.ts
Implements deploy and retrieve from context menu for ubuntu and windows
@W-17081276@
[Deploy and Retrieve End to End Tests](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/14423701597) ✅
=> feat: W-17081276 - deploy and retrieve from context menu

test/specs/deployAndRetrieve.e2e.ts, test/specs/pushAndPull.e2e.ts, test/utilities/deployAndRetrieve.ts
- Implements `SFDX: Delete This from Project and Org` using right click from both editor view and explorer view
@W-18279724@
[Deploy and Retrieve End to End Tests](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/14475283847) ✅
=> feat: W-18279724 - implement SFDX: Delete This from Project and Org using right click

test/test-setup-and-runner.ts
@W-18483821@
Test run: [Core End to End Tests](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/14941896150) ✅
=> chore: W-18483821 - avoid windows paths being parsed as URLs by the tester

package-lock.json, package.json, test/specs/runApexTests.e2e.ts
@W-18542925@
[Apex End to End Tests](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/15077131242) ✅
=> fix: W-18542925 - update selector for checkbox in runApexTests.e2e.ts

test/selfSpecs/cliCommands.test.ts, test/selfSpecs/notifications.test.ts, test/selfSpecs/settings.test.ts, test/selfSpecs/useExistingProject.test.ts, test/specs/anInitialSuite.e2e.ts, test/specs/apexLsp.e2e.ts, test/specs/apexReplayDebugger.e2e.ts, test/specs/auraLsp.e2e.ts, test/specs/authentication.e2e.ts, test/specs/createOASDoc.e2e.ts, test/specs/createProject.e2e.ts, test/specs/debugApexTests.e2e.ts, test/specs/debugLwcTests.e2e.ts, test/specs/deployAndRetrieve.e2e.ts, test/specs/lwcLsp.e2e.ts, test/specs/manifestBuilder.e2e.ts, test/specs/metadataDeployRetrieve.e2e.ts, test/specs/miscellaneous.e2e.ts, test/specs/orgBrowser.e2e.ts, test/specs/pushAndPull.e2e.ts, test/specs/runApexTests.e2e.ts, test/specs/runLwcTests.e2e.ts, test/specs/sObjectsDefinitions.e2e.ts, test/specs/sfdxProjectJson.e2e.ts, test/specs/soql.e2e.ts, test/specs/templates.e2e.ts, test/specs/trailApexReplayDebugger.e2e.ts, test/specs/visualforceLsp.e2e.ts, test/utilities/extensionUtils.ts
1. describe blocks shouldn't be async.  bad stuff happens
2. log which extensions are causing us to keep polling
=> feat: log missing ext

test/utilities/extensionUtils.ts
=> fix: @W-18520714@ - do not verify soql extension activation
